### ISSUE TITLE
Is there a way to update the citations of papers?

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/kpub#5]
I wanted to get a list of K2 papers with more than 20 citations. I ran 

``` python
import kpub
x = kpub.PublicationDB()
q = x.get_most_cited(mission='k2')
print([q[i]['citation_count'] for i in range(10)])
```

but the citation counts seem to be lower than on ADS

**Comment by mrtommyb** [comment]
Maybe this is happening

**Comment by barentsen** [comment]
Is it much lower?  The citation counts are retrieved from the metadata stored in the local database file, and is hence current as of  whenever the entire database was refreshed (done by running `kpub-export` + `kpub-import` in sequence).

A refresh happened about 3 weeks ago.  I could do this again now?

The citation count is not queried from ADS in real time when `get_most_cited` is called, because I exceeded the ADS query rate limit very quickly doing such things =(  I complained but they can somehow not make exceptions.

**Comment by mrtommyb** [comment]
lets do a refresh

**Comment by barentsen** [comment]
on it.

**Comment by mrtommyb** [comment]
when you're done could you post the papers with more than 20 citations on here and then close.

Also, I note that a few of the K2 publications are in the kepler list. Fixed one but there is at least one more
(I think I fixed this one 2014PASP..126..948V but this one is still wrong 2014ApJ...789...85H)

**Comment by mrtommyb** [comment]
Here is another that needs moving from kepler to k2
http://adsabs.harvard.edu/abs/2015ApJ...812L..11S

**Comment by barentsen** [comment]
@mrtommyb Do you mean these, or are there others?
1. [UNDERSTANDING THE EFFECTS OF STELLAR MULTIPLICITY ON THE DERIVED PLANET RADII FROM TRANSIT SURVEYS: IMPLICATIONS FOR KEPLER, K2, AND TESS](http://adsabs.harvard.edu/abs/2015ApJ...805...16C)  
2. [SUPER-NYQUIST ASTEROSEISMOLOGY OF SOLAR-LIKE OSCILLATORS WITH KEPLER AND K2 - EXPANDING THE ASTEROSEISMIC COHORT AT THE BASE OF THE RED GIANT BRANCH](http://adsabs.harvard.edu/abs/2014MNRAS.445..946C)

**Comment by mrtommyb** [comment]
No, I think the two you mention should remain in the kepler list. The ones that are in the wrong place are
- A Low Stellar Obliquity for WASP-47, a Compact Multiplanet System with a Hot Jupiter and an Ultra-short Period Planet
- Precision Asteroseismology of the Pulsating White Dwarf GD 1212 Using a Two-wheel-controlled Kepler Spacecraft

Plus it would be good if you could check that I moved this over correctly
- A Technique for Extracting Highly Precise Photometry for the Two-Wheeled Kepler Mission

**Comment by barentsen** [comment]
Understood. I'll be moving those two.  This is done on the shell as follows:

``` bash
$ kpub-delete 2015ApJ...812L..11S
$ kpub-add 2015ApJ...812L..11S
```

(the latter command asks interactively for the classification)

**Comment by mrtommyb** [comment]
Thanks

**Comment by barentsen** [comment]
@mrtommyb The database was refreshed and a script was added to generate the list of the most-cited K2 papers.  Its output is here:

https://github.com/KeplerGO/kpub/blob/master/scripts/most-popular-publications/most-cited-k2-papers.txt

(the same directory also contains a list of most-read papers)

The refresh also automatically adds the proper journal reference for articles which were previously arxiv-only.

I will push the new publication stats to the live website (`make kpub` in `KeplerScienceWebsite`) and then close this issue.

**Comment by mrtommyb** [comment]
thanks geert! perfect.

**Comment by barentsen** [comment]
Oops, Vanderburg's `A Technique for Extracting ...` was still classified as Kepler.  Fixed this now and updated `most-cited-k2-papers.txt`.  This matters because it's the second most-cited paper!  (48 citations)

**Comment by barentsen** [comment]
Website has been updated. Closing this issue.
