### ISSUE TITLE
Add missing entries to database

### ISSUE THREAD

**Issue by kcolon** [KeplerGO/kpub#6]
refereed
2017NatAs…1E..64C - http://adsabs.harvard.edu/abs/2017NatAs...1E..64C
2017arXiv170105737A - http://adsabs.harvard.edu/abs/2017arXiv170105737A
2013PhDT.......306B - http://adsabs.harvard.edu/abs/2013PhDT.......306B

conference proceedings
2016sf2a.conf..203C - http://adsabs.harvard.edu/abs/2016sf2a.conf..203C
2016csss.confE..42B - http://adsabs.harvard.edu/abs/2016csss.confE..42B

**Comment by barentsen** [comment]
Added them now!
