### ISSUE TITLE
Some of my publications to add to Kepler publication database

### ISSUE THREAD

**Issue by ericagol** [KeplerGO/kpub#7]
http://adsabs.harvard.edu/abs/2017arXiv170609849A

http://adsabs.harvard.edu/abs/2017AJ....153..265W

http://adsabs.harvard.edu/abs/2016ApJ...821...96D

(It's possible I missed these in database...)

**Comment by barentsen** [comment]
Apologies for missing these, @ericagol -- they have been added to our database just now.  Thanks!
